using System.IO;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;

/// <summary>
/// The assets are the source of truth; these constants are derived from them.
/// Scans character prefabs for Emotion/Pose IDs and character Settings assets for names,
/// then writes CharacterParameters.cs and CNames.cs. Story scripts reference
/// KateEmotions.Energetic instead of "Energetic", so a renamed or deleted asset becomes
/// a compile error, not a silent runtime miss.
///
/// One of several generators in the project (sounds, places, items, videos follow the
/// same pattern).
/// </summary>
public static class CharacterParameterGeneratorUtil
{
    private static readonly string CharacterPrefabRoot = "Assets/Resources/Characters/Prefabs";
    private static readonly string CharacterSettingsRoot = "Assets/Resources/Characters/Settings";
    private static readonly string OutputPathParameters = "Assets/Greenwood/Parameters/CharacterParameters.cs";
    private static readonly string OutputPathCNames = "Assets/Greenwood/Parameters/CNames.cs";

    [MenuItem("Tools/Generate Character Parameters")]
    public static void Generate()
    {
        GenerateCharacterParameters();
        GenerateCNames();
        AssetDatabase.Refresh();
        Debug.Log("CharacterParameters.cs / CNames.cs generated.");
    }

    private static void GenerateCharacterParameters()
    {
        string[] prefabPaths = Directory.GetFiles(CharacterPrefabRoot, "*.prefab", SearchOption.AllDirectories);

        if (prefabPaths.Length == 0)
        {
            Debug.LogWarning("No character prefabs found.");
            return;
        }

        var characterDict = new Dictionary<string, (HashSet<string> emotions, HashSet<string> poses)>();

        foreach (string path in prefabPaths)
        {
            GameObject prefab = AssetDatabase.LoadAssetAtPath<GameObject>(path);
            if (prefab == null) continue;

            Character character = prefab.GetComponent<Character>();
            if (character == null) continue;

            character.EmotionHandler.FetchEmotions();
            character.PoseHandler.FetchPoses();

            string charID = character.CharacterID;

            var emotions = new HashSet<string>();
            var poses = new HashSet<string>();

            var emotionHandler = character.EmotionHandler;
            if (emotionHandler != null)
            {
                foreach (var emotion in emotionHandler.GetComponentsInChildren<Emotion>(true))
                {
                    if (!string.IsNullOrEmpty(emotion.EmotionID))
                        emotions.Add(emotion.EmotionID);
                }
            }

            var poseHandler = character.PoseHandler;
            if (poseHandler != null)
            {
                foreach (var pose in poseHandler.GetComponentsInChildren<Pose>(true))
                {
                    if (!string.IsNullOrEmpty(pose.PoseID))
                        poses.Add(pose.PoseID);
                }
            }

            characterDict[charID] = (emotions, poses);
        }

        if (characterDict.Count == 0)
        {
            Debug.LogWarning("No character with Emotion or Pose data found.");
            return;
        }

        GenerateFileParameters(characterDict);
        EditorGUIUtility.PingObject(AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(OutputPathParameters));
    }

    private static void GenerateFileParameters(Dictionary<string, (HashSet<string> emotions, HashSet<string> poses)> characters)
    {
        EnsureDirectoryExists(OutputPathParameters);

        using StreamWriter writer = new StreamWriter(OutputPathParameters, false);
        writer.WriteLine("// Auto-generated by CharacterParameterGeneratorUtil.cs — do not edit by hand.");
        writer.WriteLine();

        writer.WriteLine("public static class CharacterParameters");
        writer.WriteLine("{");

        foreach (var (characterName, (emotions, poses)) in characters.OrderBy(e => e.Key))
        {
            if (emotions.Count > 0)
            {
                writer.WriteLine($"    public static class {characterName}Emotions");
                writer.WriteLine("    {");
                foreach (var emotion in emotions.OrderBy(e => e))
                {
                    writer.WriteLine($"        public const string {emotion} = \"{emotion}\";");
                }
                writer.WriteLine("    }");
                writer.WriteLine();
            }

            if (poses.Count > 0)
            {
                writer.WriteLine($"    public static class {characterName}Poses");
                writer.WriteLine("    {");
                foreach (var pose in poses.OrderBy(p => p))
                {
                    writer.WriteLine($"        public const string {pose} = \"{pose}\";");
                }
                writer.WriteLine("    }");
                writer.WriteLine();
            }
        }

        writer.WriteLine("}");
    }

    private static void GenerateCNames()
    {
        string[] settingPaths = Directory.GetFiles(CharacterSettingsRoot, "*.asset", SearchOption.AllDirectories);

        if (settingPaths.Length == 0)
        {
            Debug.LogWarning("No character Settings assets found.");
            return;
        }

        List<string> names = settingPaths
            .Select(Path.GetFileNameWithoutExtension)
            .Where(n => !string.IsNullOrEmpty(n))
            .Distinct()
            .OrderBy(n => n)
            .ToList();

        if (names.Count == 0)
        {
            Debug.LogWarning("No character names to write into CNames.");
            return;
        }

        EnsureDirectoryExists(OutputPathCNames);

        using StreamWriter writer = new StreamWriter(OutputPathCNames, false);
        writer.WriteLine("// Auto-generated by CharacterParameterGeneratorUtil.cs — do not edit by hand.");
        writer.WriteLine();

        writer.WriteLine("public static class CNames");
        writer.WriteLine("{");

        foreach (var name in names)
        {
            writer.WriteLine($"    public const string {name} = \"{name}\";");
        }

        writer.WriteLine("}");

        EditorGUIUtility.PingObject(AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(OutputPathCNames));
    }

    private static void EnsureDirectoryExists(string path)
    {
        string dir = Path.GetDirectoryName(path);
        if (!Directory.Exists(dir))
        {
            Directory.CreateDirectory(dir);
        }
    }
}
